#ifndef colors_H
#define colors_H

// COLORS - BACKGROUND_FOREGROUND 
// GUARDIANS BY ENIMARK - SERIBU LENTERA STUDIO 

#define	black_black				0
#define	black_darkblue			1
#define	black_darkgreen			2
#define black_torquoise			3
#define black_darkred			4
#define black_purple			5
#define black_forestgreen		6
#define black_lightgray			7
#define black_gray				8
#define black_blue				9
#define black_lightgreen		10
#define black_lightblue			11
#define black_red				12
#define black_pink				13
#define black_yellow			14
#define black_white				15

#define	darkblue_black			16
#define	darkblue_darkblue		17
#define	darkblue_darkgreen		18
#define darkblue_torquoise		19
#define darkblue_darkred		20
#define darkblue_purple			21
#define darkblue_forestgreen	22
#define darkblue_lightgray		23
#define darkblue_gray			24
#define darkblue_blue			25
#define darkblue_lightgreen		26
#define darkblue_lightblue		27
#define darkblue_red			28
#define darkblue_pink			29
#define darkblue_yellow			30
#define darkblue_white			31

#define	darkgreen_black			32
#define	darkgreen_darkblue		33
#define	darkgreen_darkgreen		34
#define darkgreen_torquoise		35
#define darkgreen_darkred		36
#define darkgreen_purple		37
#define darkgreen_forestgreen	38
#define darkgreen_lightgray		39
#define darkgreen_gray			40
#define darkgreen_blue			41
#define darkgreen_lightgreen	42
#define darkgreen_lightblue		43
#define darkgreen_red			44
#define darkgreen_pink			45
#define darkgreen_yellow		46
#define darkgreen_white			47

#define	torquoise_black			48
#define	torquoise_darkblue		49
#define	torquoise_darkgreen		50
#define torquoise_torquoise		51
#define torquoise_darkred		52
#define torquoise_purple		53
#define torquoise_forestgreen	54
#define torquoise_lightgray		55
#define torquoise_gray			56
#define torquoise_blue			57
#define torquoise_lightgreen	58
#define torquoise_lightblue		59
#define torquoise_red			60
#define torquoise_pink			61
#define torquoise_yellow		62
#define torquoise_white			63

#define	darkred_black			64
#define	darkred_darkblue		65
#define	darkred_darkgreen		66
#define darkred_torquoise		67
#define darkred_darkred			68
#define darkred_purple			69
#define darkred_forestgreen		70
#define darkred_lightgray		71
#define darkred_gray			72
#define darkred_blue			73
#define darkred_lightgreen		74
#define darkred_lightblue		75
#define darkred_red				76
#define darkred_pink			77
#define darkred_yellow			78
#define darkred_white			79

#define	purple_black			80
#define	purple_darkblue			81
#define	purple_darkgreen		82
#define purple_torquoise		83
#define purple_darkred			84
#define purple_purple			85
#define purple_forestgreen		86
#define purple_lightgray		87
#define purple_gray				88
#define purple_blue				89
#define purple_lightgreen		90
#define purple_lightblue		91
#define purple_red				92
#define purple_pink				93
#define purple_yellow			94
#define purple_white			95

#define	forestgreen_black		96
#define	forestgreen_darkblue	97
#define	forestgreen_darkgreen	98
#define forestgreen_torquoise	99
#define forestgreen_darkred		100
#define forestgreen_purple		101
#define forestgreen_forestgreen	102
#define forestgreen_lightgray	103
#define forestgreen_gray		104
#define forestgreen_blue		105
#define forestgreen_lightgreen	106
#define forestgreen_lightblue	107
#define forestgreen_red			108
#define forestgreen_pink		109
#define forestgreen_yellow		110
#define forestgreen_white		111

#define	lightgray_black			112
#define	lightgray_darkblue		113
#define	lightgray_darkgreen		114
#define lightgray_torquoise		115
#define lightgray_darkred		116
#define lightgray_purple		117
#define lightgray_forestgreen	118
#define lightgray_lightgray		119
#define lightgray_gray			120
#define lightgray_blue			121
#define lightgray_lightgreen	122
#define lightgray_lightblue		123
#define lightgray_red			124
#define lightgray_pink			125
#define lightgray_yellow		126
#define lightgray_white			127

#define	gray_black				128
#define	gray_darkblue			129
#define	gray_darkgreen			130
#define gray_torquoise			131
#define gray_darkred			132
#define gray_purple				133
#define gray_forestgreen		134
#define gray_lightgray			135
#define gray_gray				136
#define gray_blue				137
#define gray_lightgreen			138
#define gray_lightblue			139
#define gray_red				140
#define gray_pink				141
#define gray_yellow				142
#define gray_white				143

#define	blue_black				144
#define	blue_darkblue			145
#define	blue_darkgreen			146
#define blue_torquoise			147
#define blue_darkred			148
#define blue_purple				149
#define blue_forestgreen		150
#define blue_lightgray			151
#define blue_gray				152
#define blue_blue				153
#define blue_lightgreen			154
#define blue_lightblue			155
#define blue_red				156
#define blue_pink				157
#define blue_yellow				158
#define blue_white				159

#define	lightgreen_black		160
#define	lightgreen_darkblue		161
#define	lightgreen_darkgreen	162
#define lightgreen_torquoise	163
#define lightgreen_darkred		164
#define lightgreen_purple		165
#define lightgreen_forestgreen	166
#define lightgreen_lightgray	167
#define lightgreen_gray			168
#define lightgreen_blue			169
#define lightgreen_lightgreen	170
#define lightgreen_lightblue	171
#define lightgreen_red			172
#define lightgreen_pink			173
#define lightgreen_yellow		174
#define lightgreen_white		175

#define	lightblue_black			176
#define	lightblue_darkblue		177
#define	lightblue_darkgreen		178
#define lightblue_torquoise		179
#define lightblue_darkred		180
#define lightblue_purple		181
#define lightblue_forestgreen	182
#define lightblue_lightgray		183
#define lightblue_gray			184
#define lightblue_blue			185
#define lightblue_lightgreen	186
#define lightblue_lightblue		187
#define lightblue_red			188
#define lightblue_pink			189
#define lightblue_yellow		190
#define lightblue_white			191

#define	red_black				192
#define	red_darkblue			193
#define	red_darkgreen			194
#define red_torquoise			195
#define red_darkred				196
#define red_purple				197
#define red_forestgreen			198
#define red_lightgray			199
#define red_gray				200
#define red_blue				201
#define red_lightgreen			202
#define red_lightblue			203
#define red_red					204
#define red_pink				205
#define red_yellow				206
#define red_white				207

#define	pink_black				208
#define	pink_darkblue			209
#define	pink_darkgreen			210
#define pink_torquoise			211
#define pink_darkred			212
#define pink_purple				213
#define pink_forestgreen		214
#define pink_lightgray			215
#define pink_gray				216
#define pink_blue				217
#define pink_lightgreen			218
#define pink_lightblue			219
#define pink_red				220
#define pink_pink				221
#define pink_yellow				222
#define pink_white				223

#define	yellow_black			224
#define	yellow_darkblue			225
#define	yellow_darkgreen		226
#define yellow_torquoise		227
#define yellow_darkred			228
#define yellow_purple			229
#define yellow_forestgreen		230
#define yellow_lightgray		231
#define yellow_gray				232
#define yellow_blue				233
#define yellow_lightgreen		234
#define yellow_lightblue		235
#define yellow_red				236
#define yellow_pink				237
#define yellow_yellow			238
#define yellow_white			239

#define	white_black				240
#define	white_darkblue			241
#define	white_darkgreen			242
#define white_torquoise			243
#define white_darkred			244
#define white_purple			245
#define white_forestgreen		246
#define white_lightgray			247
#define white_gray				248
#define white_blue				249
#define white_lightgreen		250
#define white_lightblue			251
#define white_red				252
#define white_pink				253
#define white_yellow			254
#define white_white				255

#endif
